### ISSUE TITLE
ReadLine

### ISSUE THREAD

**Issue by ghost** [vajkayrene/WPF.Controls.Console#1]
Hi does this console control support readline?

**Comment by vajkayrene** [comment]
Hi. I primarily needed this control for a WPF/MVVM application, where I used ExecuteCommand. Readline would be a blocking call for the UI, so it is not supported. But a few minutes ago, I added Execute event for non MVVM usage. Please update the console's nuget package to get the most recent version.

Execute event gets called every time the user inputs something into the console and presses enter.  The ExecuteEventArg has a field Command where you can find the text of the command.

WPF sample:

```
<Window x:Class="TestWpfApplication.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:console="clr-namespace:WPF.Controls.Console;assembly=WPF.Controls.Console"
        Title="Console" Height="800" Width="600">
    <Grid>
        <console:ConsoleControl x:Name="MyConsoleControl" Execute="Execute" />
    </Grid>
</Window>
```

In the code behind:

```
private void Execute(object sender, WPF.Controls.Console.ExecuteEventArgs e)
{
    var command = e.Command;
    switch (command)
    {
        case "your-command":
            // Do something meaningful.
            break;
        default:
            // Do something meaningful.
            break;
    }
}
```

**Comment by ghost** [comment]
:+1: Thanks man
